routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Carbon\Carbon;
use App\Entity\User;
use Facades\App\Support\Schedule;
use App\Mail\ConfirmationOfTheRequest;
use App\Mail\DescriptiveMemoryReception;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/view/test', function () {
    $user = User::with('identities','evaluation', 'profiles')->find(2);
    //dd($user);
    Mail::to(auth()->user())->send(new DescriptiveMemoryReception($user));
    return view('mail.descriptive_memory', compact('user'));
});

Route::get('test/facade', function() {
    $dates = Schedule::get();
    dd($dates);
});

Route::get('/pdf/footer', function(){
    $date = new \DateTime();

    $IntlDateFormatter = new IntlDateFormatter(
        'es_ES',
        IntlDateFormatter::LONG,
        IntlDateFormatter::NONE
    );
    $today = $IntlDateFormatter->format($date);

    return view('pdf.footer', compact('today'));
})->name('pdf.footer');

Route::get('/pdf/global/footer', function(){
    return view('pdf.global_footer');
})->name('global.pdf.footer');

Auth::routes();

Route::middleware(['auth'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/verification/{code}', 'Verification\VerificationController@verify')->name('verification');

    Route::post('/register/perfil', 'HomeController@register')->name('perfil');

    Route::get('/profile/{user}', 'AdminUserController@index')->name('get.user.profile');
    Route::post('/create/profile', 'AdminUserController@register')->name('post.user.profile');

    Route::get('/register/memory', 'RegisterMemoryController@index')->name('register.memory');
    Route::post('/register/memory', 'RegisterMemoryController@register');

    Route::get('/register/case', 'RegisterCaseStudyController@index')->name('register.case');
    Route::post('/register/case', 'RegisterCaseStudyController@register');

    Route::get('/applicant/results/{user}', 'ResultsController@index')->name('applicant.results');
    Route::get('/admin/results/{user}', 'ResultsController@index')->name('admin.results');

    Route::get('/acceptance/{id}', 'AcceptanceDocumentController@index')->name('acceptance');
    Route::post('/acceptance/{id}', 'AcceptanceDocumentController@register');

    Route::get('/create/results/{user}', 'AdminEvaluationResultController@index')->name('create.results');
    Route::post('/create/results/{user}', 'AdminEvaluationResultController@register');

    Route::get('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@showPracticalForm')->name('create.practical');
    Route::post('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@registerPractical');

    Route::get('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@showTheoreticalForm')->name('create.theoretical');
    Route::post('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@registerTheoretical');

    Route::get('global/report/{user}','ReportController@generate')->name('global.report');
    Route::get('theoretical/report/{user}','ReportController@generateTheoretical')->name('theoretical.report');
    Route::get('practical/report/{user}','ReportController@generatePractical')->name('practical.report');

    Route::get('user/download', 'Usercontroller@download');

    Route::resource('users','UserController');

    Route::get('/user/search', 'ReportController@showSearchForm')->name('user.search');
    Route::post('/user/search', 'ReportController@search');

    Route::get('/user/enroll', 'ReportController@showSearchEnrollForm')->name('user.enroll');
    Route::post('/user/enroll', 'ReportController@searchEnroll');

    Route::get('/user/concentrated', 'ReportController@showSearchConcentratedForm')->name('user.concentrated');
    Route::post('/user/concentrated', 'ReportController@searchConcentrated');

    Route::get('/user/scores', 'ReportController@showSearchScoreForm')->name('user.score');
    Route::post('/user/scores', 'ReportController@searchScore');

    Route::post('status/evaluation', 'StatusController@change');

    Route::resource('places', 'PlaceController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('users.evaluations', 'UserEvaluationController');
    Route::resource('schedules', 'ScheduleController');
});

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Schedule;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;

class ScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schedules = Schedule::all();

        return view('schedule.index', compact('schedules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('schedule.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'date_at' => [
                'required',
                'date',
                'after_or_equal:today',
                'unique:schedules',
            ],
            'type' => [
                'required',
                'string',
            ]
        ]);

        Schedule::firstOrCreate($request->except('_token'));

        return back()->with('status', 'La fecha fue agregada');
    }

    /**
     * Display the specified resource.
     *
     * @param Schedule $schedule
     * @return void
     */
    public function show(Schedule $schedule)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Schedule $schedule
     * @return \Illuminate\Http\Response
     */
    public function edit(Schedule $schedule)
    {
        return view('schedule.edit', ['schedule' => $schedule]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Schedule $schedule
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Schedule $schedule)
    {
        $this->validate($request, [
            'date_at' => [
                'required',
                'date',
                'after_or_equal:today',
                Rule::unique('schedules')->ignore($schedule->id),
            ],
            'type' => [
                'required',
                'string',
            ]
        ]);

        $schedule->update($request->all());

        return back()->with('status', 'La fecha fue actualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Schedule $schedule
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(Schedule $schedule) : RedirectResponse
    {
        $schedule->delete();

        return back()->with('success', 'El elemento fue borrado');
    }
}

resources/views/schedule/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('layouts.alerts');
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Nueva Fecha</strong></div>

                    <div class="panel-body" id="app">
                        {!! Form::open(['route' => 'schedules.store', 'method' => 'post', 'files' => 'true']) !!}

                        <fieldset>

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('date_at') ? ' has-error' : '' }}">
                                        <label for="name">Fecha</label>
                                        <input id="name" type="date" class="form-control" name="date_at" value="{{ old('date_at') }}"  autofocus>

                                        @if ($errors->has('date_at'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('date_at') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                                        <label for="type" class="control-label">Tipo</label>
                                        {!! Form::select('type', ['teorico' => 'Teórico', 'practico' => 'Práctico'], old('type'), ['class' => 'form-control']) !!}

                                        @if ($errors->has('type'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('type') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                        </fieldset> <!-- end identity -->

                        <div class="form-group">
                            <div class="col-md-5">
                                <button type="submit" class="btn btn-primary">
                                    Agregar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/schedule/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('layouts.alerts');
                <div class="panel panel-default">
                    <div class="panel-heading">Editar Fecha</div>

                    <div class="panel-body" id="app">
                        {!! Form::model($schedule, ['route' => ['schedules.update', $schedule->id], 'method' => 'put', 'files' => 'true']) !!}

                        <fieldset>
                            <legend>Fecha</legend>

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('date_at') ? ' has-error' : '' }}">
                                        <label for="name">Fecha</label>
                                        <input id="name" type="date" class="form-control" name="date_at" value="{{ old('date_at', $schedule->date_at) }}"  autofocus>

                                        @if ($errors->has('date_at'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('date_at') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                                        <label for="type" class="control-label">Tipo</label>
                                        {!! Form::select('type', ['teorico' => 'Teórico', 'practico' => 'Práctico'], old('type'), ['class' => 'form-control']) !!}

                                        @if ($errors->has('type'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('type') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                        </fieldset> <!-- end identity -->

                        <div class="form-group">
                            <div class="col-md-5">
                                <button type="submit" class="btn btn-primary">
                                    Actualizar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/schedule/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Fechas de aplicación</strong></div>
                    <div class="panel-body">
                        @include('layouts.alerts')
                        <table class="table table-hover" id="schedule">
                            <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Tipo de examen</th>
                                <th>Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($schedules as $schedule)
                                <tr>
                                    <td>{{$schedule->date_at}}</td>
                                    <td>{{$schedule->type == 'teorico' ? 'Teórico': 'Práctico'}}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['schedules.destroy', $schedule->id]]) !!}
                                            <a data-id="{{$schedule->id}}" href="{!! route('schedules.create') !!}" class="btn btn-sm btn-default" title="Crear Sede" data-toggle="tooltip"><i class="fas fa-plus-circle"></i></a>
                                            <a href="{!! route('schedules.edit',['user' => $schedule->id]) !!}" class="btn btn-sm btn-default" title="Editar Sede" data-toggle="tooltip"><i class="far fa-edit"></i></a>
                                            <button type="submit" class="btn btn-sm btn-danger" title="Borrar Sede" data-toggle="tooltip"><i class="glyphicon glyphicon-trash"></i></button>
                                            {!! Form::close() !!}
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection