routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Carbon\Carbon;
use App\Entity\User;
use Facades\App\Support\Schedule;
use App\Mail\ConfirmationOfTheRequest;
use App\Mail\DescriptiveMemoryReception;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/view/test', function () {
    $user = User::with('identities','evaluation', 'profiles')->find(2);
    //dd($user);
    Mail::to(auth()->user())->send(new DescriptiveMemoryReception($user));
    return view('mail.descriptive_memory', compact('user'));
});

Route::get('test/facade', function() {
    $dates = Schedule::get();
    dd($dates);
});

Route::get('/pdf/footer', function(){
    $date = new \DateTime();

    $IntlDateFormatter = new IntlDateFormatter(
        'es_ES',
        IntlDateFormatter::LONG,
        IntlDateFormatter::NONE
    );
    $today = $IntlDateFormatter->format($date);

    return view('pdf.footer', compact('today'));
})->name('pdf.footer');

Route::get('/pdf/global/footer', function(){
    return view('pdf.global_footer');
})->name('global.pdf.footer');

Auth::routes();

Route::middleware(['auth'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/verification/{code}', 'Verification\VerificationController@verify')->name('verification');

    Route::post('/register/perfil', 'HomeController@register')->name('perfil');

    Route::get('/profile/{user}', 'AdminUserController@index')->name('get.user.profile');
    Route::post('/create/profile', 'AdminUserController@register')->name('post.user.profile');

    Route::get('/register/memory', 'RegisterMemoryController@index')->name('register.memory');
    Route::post('/register/memory', 'RegisterMemoryController@register');

    Route::get('/register/case', 'RegisterCaseStudyController@index')->name('register.case');
    Route::post('/register/case', 'RegisterCaseStudyController@register');

    Route::get('/applicant/results/{user}', 'ResultsController@index')->name('applicant.results');
    Route::get('/admin/results/{user}', 'ResultsController@index')->name('admin.results');

    Route::get('/acceptance/{id}', 'AcceptanceDocumentController@index')->name('acceptance');
    Route::post('/acceptance/{id}', 'AcceptanceDocumentController@register');

    Route::get('/create/results/{user}', 'AdminEvaluationResultController@index')->name('create.results');
    Route::post('/create/results/{user}', 'AdminEvaluationResultController@register');

    Route::get('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@showPracticalForm')->name('create.practical');
    Route::post('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@registerPractical');

    Route::get('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@showTheoreticalForm')->name('create.theoretical');
    Route::post('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@registerTheoretical');

    Route::get('global/report/{user}','ReportController@generate')->name('global.report');
    Route::get('theoretical/report/{user}','ReportController@generateTheoretical')->name('theoretical.report');
    Route::get('practical/report/{user}','ReportController@generatePractical')->name('practical.report');

    Route::get('user/download', 'Usercontroller@download');

    Route::resource('users','UserController');

    Route::get('/user/search', 'ReportController@showSearchForm')->name('user.search');
    Route::post('/user/search', 'ReportController@search');

    Route::get('/user/enroll', 'ReportController@showSearchEnrollForm')->name('user.enroll');
    Route::post('/user/enroll', 'ReportController@searchEnroll');

    Route::get('/user/concentrated', 'ReportController@showSearchConcentratedForm')->name('user.concentrated');
    Route::post('/user/concentrated', 'ReportController@searchConcentrated');

    Route::get('/user/scores', 'ReportController@showSearchScoreForm')->name('user.score');
    Route::post('/user/scores', 'ReportController@searchScore');

    Route::post('status/evaluation', 'StatusController@change');

    Route::resource('places', 'PlaceController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('users.evaluations', 'UserEvaluationController');
    Route::resource('schedules', 'ScheduleController');
});

app/Http/Controllers/PlaceController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Place;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class PlaceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $places = Place::all();
        return view('place.index', compact('places'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('place.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, ['name' => 'required|string|unique:places']);

        Place::firstOrCreate($request->except('_token'));

        return back()->with('status', 'La institución fue creada');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Entity\Place  $place
     * @return \Illuminate\Http\Response
     */
    public function show(Place $place)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Entity\Place  $place
     * @return \Illuminate\Http\Response
     */
    public function edit(Place $place)
    {
        return view('place.edit', compact('place'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entity\Place  $place
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Place $place)
    {
        $this->validate($request, ['name' => [
            'required',
            Rule::unique('places')->ignore($place->id),
        ]]);

        $place->update($request->all());

        return back()->with('status', 'La institución fue actualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Entity\Place  $place
     * @return \Illuminate\Http\Response
     */
    public function destroy(Place $place)
    {
        try {
            $place->canDeleted();
        } catch (\Exception $exception) {
            return back()->with('warning', $exception->getMessage());
        }
        return back()->with('success', 'El elemento fue borrado');
    }
}

resources/views/place/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('layouts.alerts');
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Nueva Sede</strong></div>

                    <div class="panel-body" id="app">
                        {!! Form::open(['route' => 'places.store', 'method' => 'post', 'files' => 'true']) !!}

                        <fieldset>

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label for="name">Nombre</label>
                                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}"  autofocus>

                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                        </fieldset> <!-- end identity -->

                        <div class="form-group">
                            <div class="col-md-5">
                                <button type="submit" class="btn btn-primary">
                                    Agregar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/place/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('layouts.alerts');
                <div class="panel panel-default">
                    <div class="panel-heading">Nueva Institución</div>

                    <div class="panel-body" id="app">
                        {!! Form::model($place, ['route' => ['places.update', $place->id], 'method' => 'put', 'files' => 'true']) !!}

                        <fieldset>
                            <legend>Institución</legend>

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label for="name">Nombre</label>
                                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name', $place->name) }}"  autofocus>

                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                            </div> <!-- END ROW -->

                        </fieldset> <!-- end identity -->

                        <div class="form-group">
                            <div class="col-md-5">
                                <button type="submit" class="btn btn-primary">
                                    Actualizar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/place/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Instituciones</strong></div>
                    <div class="panel-body">
                        @include('layouts.alerts')
                        <table class="table table-hover" id="sede">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($places as $place)
                                <tr>
                                    <td>{{$place->name}}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['places.destroy', $place->id]]) !!}
                                            <a data-id="{{$place->id}}" href="{!! route('places.create') !!}" class="btn btn-sm btn-default" title="Crear Sede" data-toggle="tooltip"><i class="fas fa-plus-circle"></i></a>
                                            <a href="{!! route('places.edit',['user' => $place->id]) !!}" class="btn btn-sm btn-default" title="Editar Sede" data-toggle="tooltip"><i class="far fa-edit"></i></a>
                                            <button type="submit" class="btn btn-sm btn-danger" title="Borrar Sede" data-toggle="tooltip"><i class="glyphicon glyphicon-trash"></i></button>
                                            {!! Form::close() !!}
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection