routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Carbon\Carbon;
use App\Entity\User;
use Facades\App\Support\Schedule;
use App\Mail\ConfirmationOfTheRequest;
use App\Mail\DescriptiveMemoryReception;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/view/test', function () {
    $user = User::with('identities','evaluation', 'profiles')->find(2);
    //dd($user);
    Mail::to(auth()->user())->send(new DescriptiveMemoryReception($user));
    return view('mail.descriptive_memory', compact('user'));
});

Route::get('test/facade', function() {
    $dates = Schedule::get();
    dd($dates);
});

Route::get('/pdf/footer', function(){
    $date = new \DateTime();

    $IntlDateFormatter = new IntlDateFormatter(
        'es_ES',
        IntlDateFormatter::LONG,
        IntlDateFormatter::NONE
    );
    $today = $IntlDateFormatter->format($date);

    return view('pdf.footer', compact('today'));
})->name('pdf.footer');

Route::get('/pdf/global/footer', function(){
    return view('pdf.global_footer');
})->name('global.pdf.footer');

Auth::routes();

Route::middleware(['auth'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/verification/{code}', 'Verification\VerificationController@verify')->name('verification');

    Route::post('/register/perfil', 'HomeController@register')->name('perfil');

    Route::get('/profile/{user}', 'AdminUserController@index')->name('get.user.profile');
    Route::post('/create/profile', 'AdminUserController@register')->name('post.user.profile');

    Route::get('/register/memory', 'RegisterMemoryController@index')->name('register.memory');
    Route::post('/register/memory', 'RegisterMemoryController@register');

    Route::get('/register/case', 'RegisterCaseStudyController@index')->name('register.case');
    Route::post('/register/case', 'RegisterCaseStudyController@register');

    Route::get('/applicant/results/{user}', 'ResultsController@index')->name('applicant.results');
    Route::get('/admin/results/{user}', 'ResultsController@index')->name('admin.results');

    Route::get('/acceptance/{id}', 'AcceptanceDocumentController@index')->name('acceptance');
    Route::post('/acceptance/{id}', 'AcceptanceDocumentController@register');

    Route::get('/create/results/{user}', 'AdminEvaluationResultController@index')->name('create.results');
    Route::post('/create/results/{user}', 'AdminEvaluationResultController@register');

    Route::get('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@showPracticalForm')->name('create.practical');
    Route::post('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@registerPractical');

    Route::get('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@showTheoreticalForm')->name('create.theoretical');
    Route::post('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@registerTheoretical');

    Route::get('global/report/{user}','ReportController@generate')->name('global.report');
    Route::get('theoretical/report/{user}','ReportController@generateTheoretical')->name('theoretical.report');
    Route::get('practical/report/{user}','ReportController@generatePractical')->name('practical.report');

    Route::get('user/download', 'Usercontroller@download');

    Route::resource('users','UserController');

    Route::get('/user/search', 'ReportController@showSearchForm')->name('user.search');
    Route::post('/user/search', 'ReportController@search');

    Route::get('/user/enroll', 'ReportController@showSearchEnrollForm')->name('user.enroll');
    Route::post('/user/enroll', 'ReportController@searchEnroll');

    Route::get('/user/concentrated', 'ReportController@showSearchConcentratedForm')->name('user.concentrated');
    Route::post('/user/concentrated', 'ReportController@searchConcentrated');

    Route::get('/user/scores', 'ReportController@showSearchScoreForm')->name('user.score');
    Route::post('/user/scores', 'ReportController@searchScore');

    Route::post('status/evaluation', 'StatusController@change');

    Route::resource('places', 'PlaceController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('users.evaluations', 'UserEvaluationController');
    Route::resource('schedules', 'ScheduleController');
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Subject;
use App\Entity\Telephone;
use App\Entity\User;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $users = User::with(['identities', 'evaluations'])->where('is_admin', false)->get();

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Entity\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Entity\User  $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(User $user)
    {
        $subjects = Subject::all()->pluck('name','id');

        return view('user.edit', compact('user', 'subjects'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entity\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, $this->useRulesAccordingToTheRequest($request));

        $subject = Subject::find($request->degree_in);

        //dd($subject);

        try {
            DB::beginTransaction();

            $user->identities()->update(
                $request->only(config('entity.identity.fields'))
            );

            $user->addresses()->update(
                $request->only(config('entity.address.fields'))
            );

            collect($request->only([
                'telephones', 'telephone_type'
            ]))->transpose()->map(function($telephonesData){
                return new Telephone([
                    'number' => $telephonesData[0],
                    'telephone_type' => $telephonesData[1],
                ]);
            })->each(function ($telephone) use($user){
                $user->telephones()->update($telephone->toArray());
            });

            $user->profiles()->update(
                $request->only(config('entity.profile.fields'))
            );

            $user->identities->addDocumentsFromRequest($request);

            $user->profiles->addDocumentsFromRequest($request);

            $user->profiles->subject_id = $subject->id;
            $user->profiles->save();

            $user->save();

            DB::commit();
            // do your database transaction here
        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            return back()->with('status', 'Se presento un error en la consulta.');
        } catch (\Exception $e) {
            DB::rollBack();
            return back()->with('status', 'Se presento un error.');
        }

        return back()->with('status', 'Su información se agrego al sistema: ¡Gracias!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Entity\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    protected function downloadFile($src){
        if(is_file($src)){
            $finfo=finfo_open(FILEINFO_MIME_TYPE);
            $content_type= finfo_file($finfo,$src);
            finfo_close($finfo);
            $file_name = basename($src).PHP_EOL;
            $size = filesize($src);
            header("Content-Type: $content_type");
            header("Content-Disposition: attachment; filename=$file_name");
            header("Content-Transfer-Encoding: binary");
            header("Content-Lenght: $size");
            readfile($src);
            return true;
        } else{
            return false;
        }
    }

    public function download(){
        if (!$this->downloadFile(app_path()."/files/memoria_descriptiva.pdf")){
            return redirect()->back();
        }
    }

    public function useRulesAccordingToTheRequest(Request $request) {
        if ($request->option == 1) {
            return [
                'first_name' => 'required|string|min:3',
                'second_name' => 'required|string|min:3',
                //'last_name' => 'alpha',
                'sex' => 'required|numeric',
                'birthday' => 'required|date|date_format:Y-m-d|before:' . Carbon::now()->toDateString(),
                'curp' => 'required|alpha_num',
                'curp_file' => 'nullable|mimes:pdf',
                'identity_card' => 'nullable|mimes:pdf',
                'street' => 'required',
                'neighborhood' => 'required',
                'postal_code' => 'required|numeric|digits:5',
                'state' => 'required|string',
                'city' => 'required|string',
                'telephones.*' => 'required|numeric|digits:10',
                'telephone_type.*' => 'required|numeric',
                'degree_in' => 'required|string',
                'option' => 'required',
                'proof_of_sufficiency_file' => 'nullable|mimes:pdf',
                //'terms' => 'required|boolean',
            ];
        } else {
            return [
                'first_name' => 'required|string|min:3',
                'second_name' => 'required|string|min:3',
                //'last_name' => 'alpha',
                'sex' => 'required|numeric',
                'birthday' => 'required|date|date_format:Y-m-d|before:' . Carbon::now()->toDateString(),
                'curp' => 'required|alpha_num',
                'curp_file' => 'nullable|mimes:pdf',
                'identity_card' => 'nullable|mimes:pdf',
                'street' => 'required',
                'neighborhood' => 'required',
                'postal_code' => 'required|numeric|digits:5',
                'state' => 'required|string',
                'city' => 'required|string',
                'telephones.*' => 'required|numeric|digits:10',
                'telephone_type.*' => 'required|numeric',
                'degree_in' => 'required|string',
                'option' => 'required',
                'curriculum' => 'nullable|required|mimes:pdf',
                'portfolio_of_evidence' => 'nullable|required|mimes:pdf',
                //'terms' => 'required|boolean',
            ];
        }
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if (session('status'))
                    <div class="alert alert-success">
                        <p>{{ session('status') }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">Usuarios</div>

                    <div class="panel-body">

                        <table class="table table-hover" id="table">
                            <thead>
                                <tr>
                                    <th>Folio</th>
                                    <th>Nombre completo</th>
                                    <th>E-mail</th>
                                    <th>Status</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr class="{{is_null($user->identities) ? 'bg-warning': ''}}">
                                    @if($user->evaluations->isEmpty())
                                        <td></td>
                                    @else
                                        <td>{{$user->evaluations->first()->code}}</td>
                                    @endif
                                    @if($user->identities == null)
                                        <td></td>
                                    @else
                                        <td>{{$user->identities->full_name}}</td>
                                    @endif
                                    <td>{{$user->email}}</td>
                                    @if($user->evaluations->isEmpty())
                                        <td></td>
                                    @else
                                        <td>{{$user->evaluations->first()->status}}</td>
                                    @endif
                                    <td class="text-center">
                                        <div class="btn-group">
                                        @if($user->identities != null)
                                            <a href="{!! route('users.edit',['user' => $user->id]) !!}" class="btn btn-sm btn-default" title="Editar Participante" data-toggle="tooltip"><i class="far fa-edit"></i></a>
                                        @else
                                            <a href="{!! route('get.user.profile',['user' => $user->id]) !!}" class="btn btn-sm btn-default" title="Agregar Perfil" data-toggle="tooltip"><i class="far fa-edit"></i></a>
                                        @endif
                                            <a href="{!! route('admin.results',['user' => $user->id]) !!}" class="btn btn-sm btn-default" title="Consultar Resultados" data-toggle="tooltip"><i class="glyphicon glyphicon-eye-open"></i></a>
                                            <a href="{!! route('acceptance', ['id' => $user->id]) !!}" class="btn btn-sm btn-default" title="Programar Evaluación" data-toggle="tooltip"><i class="glyphicon glyphicon-calendar"></i></a>
                                            <a href="{!! route('users.evaluations.index', $user) !!}" class="btn btn-sm btn-default" title="ver Evaluaciones" data-toggle="tooltip"><i class="glyphicon glyphicon-list-alt"></i></a>
                                        </div>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('layouts.alerts')

                <div class="panel panel-default">
                    <div class="panel-heading">Buscar alumnos inscritos</div>

                    <div class="panel-body">
                        {!! Form::open(['route' => 'user.search', 'method' => 'post', 'files' => 'true', 'class' => 'form-horizontal']) !!}

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">De</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Hasta</label>

                            <div class="col-md-6">
                                <input id="descriptive_memory" type="date" class="form-control" name="end_date" value="{{ old('end_date') }}" autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>

                                <br>

                            </div>

                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/search_concentrated.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('layouts.alerts')

                <div class="panel panel-default">
                    <div class="panel-heading">Concentrado de calificaciones</div>

                    <div class="panel-body">
                        {!! Form::open(['route' => 'user.concentrated', 'method' => 'post', 'files' => 'true', 'class' => 'form-horizontal']) !!}

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">De</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Hasta</label>

                            <div class="col-md-6">
                                <input id="descriptive_memory" type="date" class="form-control" name="end_date" value="{{ old('end_date') }}" autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>

                                <br>

                            </div>

                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/search_enroll.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('layouts.alerts')

                <div class="panel panel-default">
                    <div class="panel-heading">Matricula</div>

                    <div class="panel-body">
                        {!! Form::open(['route' => 'user.enroll', 'method' => 'post', 'files' => 'true', 'class' => 'form-horizontal']) !!}

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">De</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Hasta</label>

                            <div class="col-md-6">
                                <input id="descriptive_memory" type="date" class="form-control" name="end_date" value="{{ old('end_date') }}" autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>

                                <br>

                            </div>

                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/search_score.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('layouts.alerts')

                <div class="panel panel-default">
                    <div class="panel-heading">Calificaciones</div>

                    <div class="panel-body">
                        {!! Form::open(['route' => 'user.score', 'method' => 'post', 'files' => 'true', 'class' => 'form-horizontal']) !!}

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">De</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Hasta</label>

                            <div class="col-md-6">
                                <input id="descriptive_memory" type="date" class="form-control" name="end_date" value="{{ old('end_date') }}" autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>

                                <br>

                            </div>

                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/show_search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('layouts.alerts')
                <div class="panel panel-default">
                    <div class="panel-heading">Usuarios</div>

                    <div class="panel-body">

                        {!! Form::open(['route' => 'user.search', 'method' => 'post', 'files' => 'true', 'class' => 'form-horizontal']) !!}

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">De</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Hasta</label>

                            <div class="col-md-6">
                                <input id="descriptive_memory" type="date" class="form-control" name="end_date" value="{{ old('end_date') }}" autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>

                                <br>

                            </div>

                        </div>
                        {!! Form::close() !!}

                        <table class="table table-hover" id="table">
                            <thead>
                            <tr>
                                <th>Folio</th>
                                <th>Nombre completo</th>
                                <th>Fecha de examen</th>
                                <th>Materia</th>
                                <th>Sede</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    @if(empty($user->evaluation))
                                        <td></td>
                                    @else
                                        <td>{{$user->evaluation->code}}</td>
                                    @endif
                                    <td>{{$user->identities->full_name}}</td>
                                    <td>{{\App\Support\FormatDate::from($user->evaluation->scheduled_date)}}</td>
                                    <td>{{$user->profiles->subject->name}}</td>
                                    <td>{{$user->evaluation->place->name}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection