routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Carbon\Carbon;
use App\Entity\User;
use Facades\App\Support\Schedule;
use App\Mail\ConfirmationOfTheRequest;
use App\Mail\DescriptiveMemoryReception;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/view/test', function () {
    $user = User::with('identities','evaluation', 'profiles')->find(2);
    //dd($user);
    Mail::to(auth()->user())->send(new DescriptiveMemoryReception($user));
    return view('mail.descriptive_memory', compact('user'));
});

Route::get('test/facade', function() {
    $dates = Schedule::get();
    dd($dates);
});

Route::get('/pdf/footer', function(){
    $date = new \DateTime();

    $IntlDateFormatter = new IntlDateFormatter(
        'es_ES',
        IntlDateFormatter::LONG,
        IntlDateFormatter::NONE
    );
    $today = $IntlDateFormatter->format($date);

    return view('pdf.footer', compact('today'));
})->name('pdf.footer');

Route::get('/pdf/global/footer', function(){
    return view('pdf.global_footer');
})->name('global.pdf.footer');

Auth::routes();

Route::middleware(['auth'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/verification/{code}', 'Verification\VerificationController@verify')->name('verification');

    Route::post('/register/perfil', 'HomeController@register')->name('perfil');

    Route::get('/profile/{user}', 'AdminUserController@index')->name('get.user.profile');
    Route::post('/create/profile', 'AdminUserController@register')->name('post.user.profile');

    Route::get('/register/memory', 'RegisterMemoryController@index')->name('register.memory');
    Route::post('/register/memory', 'RegisterMemoryController@register');

    Route::get('/register/case', 'RegisterCaseStudyController@index')->name('register.case');
    Route::post('/register/case', 'RegisterCaseStudyController@register');

    Route::get('/applicant/results/{user}', 'ResultsController@index')->name('applicant.results');
    Route::get('/admin/results/{user}', 'ResultsController@index')->name('admin.results');

    Route::get('/acceptance/{id}', 'AcceptanceDocumentController@index')->name('acceptance');
    Route::post('/acceptance/{id}', 'AcceptanceDocumentController@register');

    Route::get('/create/results/{user}', 'AdminEvaluationResultController@index')->name('create.results');
    Route::post('/create/results/{user}', 'AdminEvaluationResultController@register');

    Route::get('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@showPracticalForm')->name('create.practical');
    Route::post('/create/practical/{user}/{evaluation}', 'AdminEvaluationResultController@registerPractical');

    Route::get('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@showTheoreticalForm')->name('create.theoretical');
    Route::post('/create/theoretical/{user}/{evaluation}', 'AdminEvaluationResultController@registerTheoretical');

    Route::get('global/report/{user}','ReportController@generate')->name('global.report');
    Route::get('theoretical/report/{user}','ReportController@generateTheoretical')->name('theoretical.report');
    Route::get('practical/report/{user}','ReportController@generatePractical')->name('practical.report');

    Route::get('user/download', 'Usercontroller@download');

    Route::resource('users','UserController');

    Route::get('/user/search', 'ReportController@showSearchForm')->name('user.search');
    Route::post('/user/search', 'ReportController@search');

    Route::get('/user/enroll', 'ReportController@showSearchEnrollForm')->name('user.enroll');
    Route::post('/user/enroll', 'ReportController@searchEnroll');

    Route::get('/user/concentrated', 'ReportController@showSearchConcentratedForm')->name('user.concentrated');
    Route::post('/user/concentrated', 'ReportController@searchConcentrated');

    Route::get('/user/scores', 'ReportController@showSearchScoreForm')->name('user.score');
    Route::post('/user/scores', 'ReportController@searchScore');

    Route::post('status/evaluation', 'StatusController@change');

    Route::resource('places', 'PlaceController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('evaluations', 'EvaluationController');
    Route::resource('users.evaluations', 'UserEvaluationController');
    Route::resource('schedules', 'ScheduleController');
});

resources/views/layouts/alerts.blade.php
@if (session('status'))
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ session('status') }}</p>
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ session('success') }}</p>
    </div>
@endif

@if (session('info'))
    <div class="alert alert-info alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ session('info') }}</p>
    </div>
@endif

@if (session('warning'))
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ session('warning') }}</p>
    </div>
@endif

@if (session('danger'))
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ session('danger') }}</p>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" media="all">

    <!-- Latest compiled and minified CSS of bootstrap select-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
    <!--  Datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-colvis-1.5.1/b-flash-1.5.1/b-html5-1.5.1/b-print-1.5.1/datatables.min.css"/>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Entrar</a></li>
                            <li><a href="{{ route('register') }}">Registro</a></li>
                        @else
                            @if(Auth::user()->is_admin === true)
                                <li><a href="{{ route('schedules.index') }}">Fechas disponibles</a></li>
                                <li><a href="{{ route('places.index') }}">Instituciones</a></li>
                                <li><a href="{{ route('subjects.index') }}">Licenciaturas</a></li>
                                <li><a href="{{ route('users.index') }}">Usuarios</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                        Reportes <span class="caret"></span>
                                    </a>

                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{{route('user.search')}}">Alumnos inscritos</a></li>
                                        <li><a href="{{route('user.enroll')}}">Matricula</a></li>
                                        <li><a href="{{route('user.concentrated')}}">Calificaciones</a></li>
                                    </ul>
                                </li>
                            @endif

                            @if(Auth::user()->is_admin == false)
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                            Registrar <span class="caret"></span>
                                        </a>

                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{{route('home')}}">Solicitud</a></li>
                                            <li><a href="{{route('register.memory')}}">memoria descriptiva</a></li>
                                            <li><a href="{{route('register.case')}}">responsiva caso práctico</a></li>
                                        </ul>
                                    </li>
                            @endif

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->email }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Salir
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    {{--<script src="{{ asset('js/app.js') }}"></script>--}}
    <!-- Latest compiled and minified JavaScript -->

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

    <script src="https://unpkg.com/vue@3"></script>
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{asset('js/laravel-delete.js')}}"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{{asset('js/bootstrap-filestyle.min.js')}}"> </script>
    <!-- DataTables JS -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-colvis-1.5.1/b-flash-1.5.1/b-html5-1.5.1/b-print-1.5.1/datatables.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.27.0/dist/sweetalert2.all.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/i18n/defaults-*.min.js"></script>

    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);

        Vue.createApp({
            data() {
                return {
                    picked: 1
                }
            }
        }).mount('#app')

        Vue.createApp({
            data() {
                return {
                    selected: ''
                }
            }
        }).mount('#result_form')

    </script>

    <script>
        $(document).ready(function() {
            $('#table').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json"
                },
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'pdf',
                        text: 'PDF',
                        exportOptions: {
                            modifier: {
                                page: 'current'
                            }
                        }
                    }
                ]
            });

            $('#sede').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json"
                },
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Sede',
                        className: 'btn btn-success',
                        action: function ( e, dt, node, config ) {
                            window.location = '{{route('places.create')}}';
                        }
                    }
                ]
            });

            $('#schedule').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json"
                },
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Fecha',
                        className: 'btn btn-success',
                        action: function ( e, dt, node, config ) {
                            window.location = '{{route('schedules.create')}}';
                        }
                    }
                ]
            });

            $('#subject').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json"
                },
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Licenciatura',
                        className: 'btn btn-success',
                        action: function ( e, dt, node, config ) {
                            window.location = '{{route('subjects.create')}}';
                        }
                    }
                ]
            });
        } );
    </script>

    <script>
        $(":file").filestyle({buttonName: "btn-primary", buttonText: "Subir Archivo"});

        /*$('.selectpicker').selectpicker({});*/

    </script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" media="all">

    <!-- Optional theme -->
    <!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    -->

    @yield('styles')

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

@section('content')
@endsection

</body>
</html>